### ISSUE TITLE
Listener for hidden service published event

### ISSUE THREAD

**Issue by blabno** [JesusMcCloud/netlayer#14]
I want to publish hidden service that would proxy traffic from Tor to a service exposed on my local port.
```
Tor.getDefault().publishHiddenService("api", 80, 8080);
```
How can I add listener to know that service has been published?

**Comment by freimair** [comment]
support has been added in 8ba19fbbb5e11985dbeff4c1616f84c4805cf8ff (and is thus available since [v0.6.4](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6.4)) along with an example:
```
final HsContainer hsContainer = Tor.getDefault().publishHiddenService("hsDirName", 80, 8080);

hsContainer.getHandler().attachHSReadyListener(hsContainer.getHostname(), () -> {
      System.err.println("HiddenService is online");
      return null;
});
```
