### ISSUE TITLE
Add torrc Override

### ISSUE THREAD

**Issue by JesusMcCloud** [JesusMcCloud/netlayer#4]
Currently, there is no way to override values in the default torrc.
An easy way to provide overrides and additional default configs needs to be implemented.
Simply pushing configuration directives through the Tor control connection is not the way to go, as the defaults need to be set prior to starting tor.
A simple way would be to just implement something like `Tor.setDefaultConfig(property: String, value: String)` to add value to the torrc file.
In addition, `Tor.setTorrc(configuration: String)` and `Tor.setTorrc(torrc: File)` should be implemented to provide a full torrc.

In both cases, the following configuration directives must not be overridden:
```
 AvoidDiskWrites 1
 PidFile pid
 RunAsDaemon 1
 SOCKSPort auto

**Comment by ManfredKarrer** [comment]
Yes would be great to get that. We also had an issue for that feature request:
https://github.com/bisq-network/exchange/issues/965

**Comment by JesusMcCloud** [comment]
Support added in [0.4.1](https://github.com/JesusMcCloud/netlayer/releases/tag/0.4.1)

**Comment by ManfredKarrer** [comment]
Cool! Will merge it in Bisq soon.
